services:
  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sixsotok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
