import { Listing } from '@/types/listing';

const IMG1 = 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop';
const IMG2 = 'https://images.unsplash.com/photo-1524338198850-8b2fa59a8c08?q=80&w=1000&auto=format&fit=crop';
const IMG3 = 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=1000&auto=format&fit=crop';
const IMG4 = 'https://images.unsplash.com/photo-1500076656116-558758c991c1?q=80&w=1000&auto=format&fit=crop';
const IMG5 = 'https://images.unsplash.com/photo-1629196914548-5214f2e2c2e5?q=80&w=1000&auto=format&fit=crop';

export const mockListings: Listing[] = [
  // АЛМАТЫ
  {
    id: 'alm-1', slug: 'uchastok-igs-almaty-10',
    title: 'Участок ИЖС в элитном районе Алматы',
    price: 15000000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Алматы, Наурызбайский район',
    lat: 43.24, lng: 76.88,
    image: IMG1, images: [IMG1, IMG5], communications: ['Свет', 'Вода', 'Газ'],
    cadastralNumber: '20-315-094-101', isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    reliefType: 'Ровный', plotShape: 'Прямоугольный', frontWidth: 25, depth: 40,
    description: 'Ровный участок 10 соток в экологически чистом районе Алматы. Все коммуникации на участке.',
    seller: { name: 'Best Realty KZ', phone: '+7 701 123 45 67', isAgency: true, registerDate: '2021 года' },
    createdAt: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'alm-2', slug: 'uchastok-kommercia-almaty-25',
    title: 'Коммерческий участок у проспекта Аль-Фараби',
    price: 85000000, area: 25, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Алматы, Бостандыкский район',
    lat: 43.21, lng: 76.93,
    image: IMG3, images: [IMG3], communications: ['Свет', 'Вода', 'Канализация'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Асель', phone: '+7 701 999 88 77', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'alm-3', slug: 'dacha-kaskelen-6',
    title: 'Дачный участок с садом в Каскелене',
    price: 4500000, area: 6, landType: 'Дача', purpose: 'Сельхоз',
    location: 'Каскелен, Алматинская обл.',
    lat: 43.20, lng: 76.62,
    image: IMG2, images: [IMG2], communications: ['Свет', 'Поливная вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Анна', phone: '+7 775 987 65 43', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },

  // АСТАНА
  {
    id: 'ast-1', slug: 'uchastok-igs-astana-12',
    title: 'Участок ИЖС на левом берегу Астаны',
    price: 18000000, area: 12, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Астана, Есильский район',
    lat: 51.19, lng: 71.48,
    image: IMG1, images: [IMG1], communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    reliefType: 'Ровный', plotShape: 'Прямоугольный', frontWidth: 30, depth: 40,
    seller: { name: 'Nurlan', phone: '+7 702 111 22 33', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'ast-2', slug: 'kommercia-astana-50',
    title: 'Коммерческий участок под офис в Астане',
    price: 200000000, area: 50, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Астана, Алматинский район',
    lat: 51.15, lng: 71.42,
    image: IMG3, communications: ['Свет', 'Вода', 'Канализация', 'Газ'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Capital Invest', phone: '+7 702 500 60 70', isAgency: true, registerDate: '2019 года' },
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'ast-3', slug: 'lph-astana-8',
    title: 'ЛПХ участок на окраине Астаны',
    price: 6000000, area: 8, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Астана, Сарыаркинский район',
    lat: 51.22, lng: 71.52,
    image: IMG4, communications: ['Свет'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Дамир', phone: '+7 702 333 44 55', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },

  // ШЫМКЕНТ
  {
    id: 'shym-1', slug: 'uchastok-igs-shymkent-10',
    title: 'Участок ИЖС в Шымкенте, тихий район',
    price: 9500000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Шымкент, Аль-Фарабийский район',
    lat: 42.32, lng: 69.59,
    image: IMG5, images: [IMG5], communications: ['Свет', 'Вода', 'Газ'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Мирас', phone: '+7 725 100 20 30', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'shym-2', slug: 'kommercia-shymkent-40',
    title: 'Участок под торговый центр в Шымкенте',
    price: 150000000, area: 40, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Шымкент, Енбекшинский район',
    lat: 42.29, lng: 69.62,
    image: IMG3, communications: ['Свет', 'Вода', 'Канализация'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: true,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'South Invest', phone: '+7 725 555 77 88', isAgency: true, registerDate: '2020 года' },
    createdAt: new Date(Date.now() - 500000000).toISOString(),
  },
  {
    id: 'shym-3', slug: 'lph-shymkent-15',
    title: 'ЛПХ участок в пригороде Шымкента',
    price: 4800000, area: 15, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Шымкент, Туркестанская обл.',
    lat: 42.35, lng: 69.55,
    image: IMG4, communications: ['Свет', 'Скважина'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Нурия', phone: '+7 725 700 80 90', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 520000000).toISOString(),
  },

  // ҚАРАҒАНДЫ
  {
    id: 'kgd-1', slug: 'uchastok-igs-karaganda-15',
    title: 'Участок ИЖС в центре Қарағанды',
    price: 7000000, area: 15, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Қарағанды, Казыбек би район',
    lat: 49.83, lng: 73.10,
    image: IMG1, communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Руслан', phone: '+7 721 200 30 40', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 600000000).toISOString(),
  },
  {
    id: 'kgd-2', slug: 'lph-karaganda-20',
    title: 'ЛПХ участок под хозяйство в Карагандинской обл.',
    price: 3500000, area: 20, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Қарағанды, Бухар-Жырауский район',
    lat: 49.91, lng: 73.25,
    image: IMG4, communications: ['Свет', 'Скважина'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Ержан', phone: '+7 721 444 55 66', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 650000000).toISOString(),
  },

  // АКТОБЕ
  {
    id: 'akto-1', slug: 'uchastok-igs-aktobe-10',
    title: 'Участок ИЖС в новом микрорайоне Актобе',
    price: 5500000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Актобе, Алматинский район',
    lat: 50.29, lng: 57.22,
    image: IMG5, communications: ['Свет', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Болат', phone: '+7 713 100 20 30', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 700000000).toISOString(),
  },
  {
    id: 'akto-2', slug: 'kommercia-aktobe-30',
    title: 'Коммерческий участок у трассы М32 в Актобе',
    price: 40000000, area: 30, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Актобе, Промышленная зона',
    lat: 50.25, lng: 57.15,
    image: IMG3, communications: ['Свет', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: true,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'West Realty', phone: '+7 713 500 60 70', isAgency: true, registerDate: '2021 года' },
    createdAt: new Date(Date.now() - 750000000).toISOString(),
  },

  // ТАРАЗ
  {
    id: 'tar-1', slug: 'uchastok-igs-taraz-8',
    title: 'Участок ИЖС в Таразе, коммуникации рядом',
    price: 6000000, area: 8, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Тараз, Жамбылский район',
    lat: 42.90, lng: 71.38,
    image: IMG1, communications: ['Свет', 'Газ'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Самат', phone: '+7 726 100 00 11', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 800000000).toISOString(),
  },
  {
    id: 'tar-2', slug: 'dacha-taraz-6',
    title: 'Дача в пригороде Тараза',
    price: 2500000, area: 6, landType: 'Дача', purpose: 'Сельхоз',
    location: 'Тараз, Жамбылская обл.',
    lat: 42.87, lng: 71.44,
    image: IMG2, communications: ['Свет', 'Поливная вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Гульнар', phone: '+7 726 200 30 44', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 850000000).toISOString(),
  },

  // ПАВЛОДАР
  {
    id: 'pvl-1', slug: 'uchastok-igs-pavlodar-12',
    title: 'Участок ИЖС в Павлодаре у реки Иртыш',
    price: 8500000, area: 12, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Павлодар, Ленинский район',
    lat: 52.29, lng: 76.97,
    image: IMG1, images: [IMG1], communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Алия', phone: '+7 718 300 40 50', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 900000000).toISOString(),
  },
  {
    id: 'pvl-2', slug: 'lph-pavlodar-25',
    title: 'Большой ЛПХ участок под Павлодаром',
    price: 4000000, area: 25, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Павлодар, Качирский район',
    lat: 52.35, lng: 77.05,
    image: IMG4, communications: ['Свет'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Тимур', phone: '+7 718 500 60 77', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 950000000).toISOString(),
  },

  // УСТЬ-КАМЕНОГОРСК
  {
    id: 'ust-1', slug: 'uchastok-igs-ust-12',
    title: 'Участок ИЖС в Усть-Каменогорске',
    price: 9000000, area: 12, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Усть-Каменогорск, Ульбинский район',
    lat: 49.96, lng: 82.62,
    image: IMG5, communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Николай', phone: '+7 723 100 20 30', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 1000000000).toISOString(),
  },
  {
    id: 'ust-2', slug: 'dacha-ust-8',
    title: 'Дача с домиком у реки Иртыш',
    price: 5000000, area: 8, landType: 'Дача', purpose: 'Сельхоз',
    location: 'Усть-Каменогорск, ВКО',
    lat: 50.01, lng: 82.70,
    image: IMG2, communications: ['Свет', 'Скважина'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Ирина', phone: '+7 723 400 50 60', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 1050000000).toISOString(),
  },

  // СЕМЕЙ
  {
    id: 'sem-1', slug: 'uchastok-igs-semey-10',
    title: 'Участок ИЖС в Семее',
    price: 6500000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Семей, Абайский район',
    lat: 50.43, lng: 80.26,
    image: IMG1, communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Даурен', phone: '+7 722 100 11 22', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 1100000000).toISOString(),
  },
  {
    id: 'sem-2', slug: 'lph-semey-15',
    title: 'ЛПХ в Семейском районе',
    price: 3000000, area: 15, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Семей, ВКО',
    lat: 50.48, lng: 80.32,
    image: IMG4, communications: ['Свет'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Серик', phone: '+7 722 300 44 55', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 1150000000).toISOString(),
  },

  // КОСТАНАЙ
  {
    id: 'kos-1', slug: 'uchastok-igs-kostanay-12',
    title: 'Участок под строительство дома в Костанае',
    price: 7000000, area: 12, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Костанай, Костанайский район',
    lat: 53.22, lng: 63.63,
    image: IMG5, communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Андрей', phone: '+7 714 100 22 33', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 1200000000).toISOString(),
  },
  {
    id: 'kos-2', slug: 'selhoz-kostanay-50',
    title: 'Сельхоз угодья в Костанайской области',
    price: 12000000, area: 50, landType: 'Сельхоз', purpose: 'Сельхоз',
    location: 'Костанай, Федоровский район',
    lat: 53.35, lng: 63.75,
    image: IMG4, communications: ['Свет'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Agro North', phone: '+7 714 400 50 60', isAgency: true, registerDate: '2020 года' },
    createdAt: new Date(Date.now() - 1250000000).toISOString(),
  },

  // АТЫРАУ
  {
    id: 'atr-1', slug: 'uchastok-igs-atyrau-10',
    title: 'Участок ИЖС в Атырау, нефтяной район',
    price: 22000000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Атырау, Жылыойский район',
    lat: 47.11, lng: 51.91,
    image: IMG1, communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Мурат', phone: '+7 712 100 20 30', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 1300000000).toISOString(),
  },
  {
    id: 'atr-2', slug: 'kommercia-atyrau-20',
    title: 'Коммерческий участок в промзоне Атырау',
    price: 60000000, area: 20, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Атырау, Промышленная зона',
    lat: 47.08, lng: 51.87,
    image: IMG3, communications: ['Свет', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Caspian Realty', phone: '+7 712 500 60 70', isAgency: true, registerDate: '2021 года' },
    createdAt: new Date(Date.now() - 1350000000).toISOString(),
  },

  // АКТАУ
  {
    id: 'akt-1', slug: 'uchastok-igs-aktau-8',
    title: 'Участок ИЖС у Каспийского моря в Актау',
    price: 16000000, area: 8, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Актау, Мангистауская обл.',
    lat: 43.65, lng: 51.19,
    image: IMG5, images: [IMG5], communications: ['Свет', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: true, hasRoadAccess: true,
    seller: { name: 'Бекзат', phone: '+7 729 100 20 30', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 1400000000).toISOString(),
  },
  {
    id: 'akt-2', slug: 'kommercia-aktau-30',
    title: 'Коммерческий участок у порта Актау',
    price: 90000000, area: 30, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Актау, Портовая зона',
    lat: 43.61, lng: 51.17,
    image: IMG3, communications: ['Свет', 'Вода', 'Дорога'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Mangyshlak Invest', phone: '+7 729 500 60 70', isAgency: true, registerDate: '2020 года' },
    createdAt: new Date(Date.now() - 1450000000).toISOString(),
  },

  // КЫЗЫЛОРДА
  {
    id: 'kyz-1', slug: 'uchastok-igs-kyzylorda-10',
    title: 'Участок ИЖС в Кызылорде',
    price: 5000000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Кызылорда, Кызылординский район',
    lat: 44.85, lng: 65.51,
    image: IMG1, communications: ['Свет', 'Газ'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Бахыт', phone: '+7 724 100 20 30', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 1500000000).toISOString(),
  },
  {
    id: 'kyz-2', slug: 'selhoz-kyzylorda-100',
    title: 'Сельхоз участок у реки Сырдарья',
    price: 8000000, area: 100, landType: 'Сельхоз', purpose: 'Сельхоз',
    location: 'Кызылорда, Сырдарьинский район',
    lat: 44.90, lng: 65.58,
    image: IMG4, communications: ['Свет'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'AgroKZ', phone: '+7 724 400 50 60', isAgency: true, registerDate: '2021 года' },
    createdAt: new Date(Date.now() - 1550000000).toISOString(),
  },

  // ПЕТРОПАВЛОВСК
  {
    id: 'ptr-1', slug: 'uchastok-igs-petropavlovsk-10',
    title: 'Участок ИЖС в Петропавловске',
    price: 6000000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Петропавловск, Кызылжарский район',
    lat: 54.87, lng: 69.13,
    image: IMG5, communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Владимир', phone: '+7 715 100 20 30', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 1600000000).toISOString(),
  },
  {
    id: 'ptr-2', slug: 'lph-petropavlovsk-20',
    title: 'ЛПХ участок в окрестностях Петропавловска',
    price: 2800000, area: 20, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Петропавловск, СКО',
    lat: 54.92, lng: 69.20,
    image: IMG4, communications: ['Свет'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Татьяна', phone: '+7 715 300 40 50', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 1650000000).toISOString(),
  },

  // ТАЛДЫКОРГАН
  {
    id: 'tld-1', slug: 'uchastok-igs-taldykorgan-8',
    title: 'Участок ИЖС в Талдыкоргане',
    price: 8000000, area: 8, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Талдыкорган, Алматинская обл.',
    lat: 44.98, lng: 78.38,
    image: IMG1, communications: ['Свет', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Саян', phone: '+7 728 100 20 30', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 1700000000).toISOString(),
  },
  {
    id: 'tld-2', slug: 'dacha-taldykorgan-6',
    title: 'Дача в горах Алматинской области',
    price: 3500000, area: 6, landType: 'Дача', purpose: 'Сельхоз',
    location: 'Талдыкорган, Карасайский район',
    lat: 44.93, lng: 78.43,
    image: IMG2, communications: ['Свет', 'Скважина'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Жанна', phone: '+7 728 400 55 66', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 1750000000).toISOString(),
  },

  // ТУРКЕСТАН
  {
    id: 'trk-1', slug: 'uchastok-igs-turkestan-10',
    title: 'Участок ИЖС в Туркестане',
    price: 5500000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Туркестан, Туркестанская обл.',
    lat: 43.30, lng: 68.27,
    image: IMG5, communications: ['Свет', 'Газ'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: false, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Жандос', phone: '+7 725 900 10 20', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 1800000000).toISOString(),
  },
  {
    id: 'trk-2', slug: 'kommercia-turkestan-25',
    title: 'Коммерческий участок у вокзала Туркестан',
    price: 35000000, area: 25, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Туркестан, Туркестанская обл.',
    lat: 43.27, lng: 68.31,
    image: IMG3, communications: ['Свет', 'Вода', 'Дорога'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: true,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'South KZ Invest', phone: '+7 725 500 70 80', isAgency: true, registerDate: '2021 года' },
    createdAt: new Date(Date.now() - 1850000000).toISOString(),
  },

  // КОКШЕТАУ
  {
    id: 'kok-1', slug: 'uchastok-igs-kokshetau-10',
    title: 'Участок ИЖС в Кокшетау у озера',
    price: 6500000, area: 10, landType: 'ИЖС', purpose: 'ИЖС',
    location: 'Кокшетау, Акмолинская обл.',
    lat: 53.28, lng: 69.39,
    image: IMG1, images: [IMG1], communications: ['Свет', 'Газ', 'Вода'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true, hasGas: true, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Арман', phone: '+7 716 100 20 30', isAgency: false, registerDate: '2022 года' },
    createdAt: new Date(Date.now() - 1900000000).toISOString(),
  },
  {
    id: 'kok-2', slug: 'dacha-kokshetau-8',
    title: 'Дача на берегу озера Копа в Кокшетау',
    price: 4500000, area: 8, landType: 'Дача', purpose: 'Сельхоз',
    location: 'Кокшетау, Акмолинская обл.',
    lat: 53.31, lng: 69.45,
    image: IMG2, communications: ['Свет', 'Скважина'],
    isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    seller: { name: 'Светлана', phone: '+7 716 300 40 55', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 1950000000).toISOString(),
  },

  // ТАЛГАР (пригород Алматы)
  {
    id: 'tlg-1', slug: 'commerce-talgar-50',
    title: 'Участок вдоль трассы под СТО в Талгаре',
    price: 120000000, area: 50, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Талгар, Алматинская обл.',
    lat: 43.30, lng: 77.25,
    image: IMG3, images: [],
    communications: ['Свет', 'Вода', 'Канализация'],
    cadastralNumber: '20-315-094-333', isPledged: true, hasEncumbrances: true, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: true, isOnRedLine: true,
    landCategory: 'Земли промышленности',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: true, hasRoadAccess: true,
    reliefType: 'Ровный', plotShape: 'Нестандартный', frontWidth: 100, depth: 50,
    suitableFor: ['бизнес', 'склад', 'инвестиция'],
    description: 'Коммерческий участок 50 соток вдоль оживленной трассы в Талгаре. Идеально под СТО или торговую базу.',
    seller: { name: 'CommercialInvest', phone: '+7 707 555 11 22', isAgency: true, registerDate: '2019 года' },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },

  // БОРАЛДАЙ
  {
    id: 'brl-1', slug: 'lph-boraldai-15',
    title: 'Участок под ЛПХ в Боралдае, ровный',
    price: 8000000, area: 15, landType: 'Сельхоз', purpose: 'ЛПХ',
    location: 'Боралдай, Алматинская обл.',
    lat: 43.39, lng: 76.83,
    image: IMG4, images: [],
    communications: ['Свет', 'Скважина'],
    cadastralNumber: '20-315-094-444', isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Частная собственность', isDivisible: false, isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: false, hasRoadAccess: true,
    reliefType: 'Ровный', plotShape: 'Прямоугольный', frontWidth: 30, depth: 50,
    suitableFor: ['дом', 'огород'],
    description: 'Отличный участок для ведения личного подсобного хозяйства в Боралдае.',
    seller: { name: 'Ерлан', phone: '+7 747 111 00 99', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },

  // КОНАЕВ
  {
    id: 'knv-1', slug: 'baza-konaev-100',
    title: 'Зона отдыха у воды в Конаеве',
    price: 250000000, area: 100, landType: 'Коммерция', purpose: 'Коммерция',
    location: 'Конаев, Алматинская обл.',
    lat: 43.86, lng: 77.08,
    image: IMG1, images: [],
    communications: ['Свет', 'Вода'],
    cadastralNumber: '20-315-094-555', isPledged: false, hasEncumbrances: false, hasStateAct: true,
    ownershipType: 'Аренда', isDivisible: true, isOnRedLine: false,
    landCategory: 'Земли рекреационного назначения',
    hasElectricity: true, hasGas: false, hasWater: true, hasSewer: true, hasRoadAccess: true,
    reliefType: 'Ровный', plotShape: 'Прямоугольный', frontWidth: 50, depth: 200,
    suitableFor: ['инвестиция', 'бизнес'],
    description: 'Участок на берегу Капчагая в Конаеве под строительство зоны отдыха.',
    seller: { name: 'Игорь', phone: '+7 705 333 44 55', isAgency: false, registerDate: '2020 года' },
    createdAt: new Date(Date.now() - 300000000).toISOString(),
  },
];

// allListings = полный список без дублей (используется в каталоге и счётчиках)
export const allListings = mockListings;
