import { Listing } from '@/types/listing';

export const mockListings: Listing[] = [
  {
    id: '1',
    slug: 'uchastok-igs-almaty-10-sotok',
    title: 'Участок ИЖС правильной формы в элитном районе',
    price: 15000000,
    area: 10,
    landType: 'ИЖС',
    purpose: 'ИЖС',
    location: 'Алматы, Наурызбайский район',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1629196914548-5214f2e2c2e5?q=80&w=1000&auto=format&fit=crop'
    ],
    communications: ['Свет', 'Вода', 'Газ'],
    cadastralNumber: '20-315-094-111',
    isPledged: false,
    hasEncumbrances: false,
    hasStateAct: true,
    ownershipType: 'Частная собственность',
    isDivisible: true,
    isOnRedLine: false,
    landCategory: 'Земли населенных пунктов',
    hasElectricity: true,
    hasGas: true,
    hasWater: true,
    hasSewer: true,
    hasRoadAccess: true,
    reliefType: 'Ровный',
    plotShape: 'Прямоугольный',
    frontWidth: 25,
    depth: 40,
    canChangePurpose: false,
    suitableFor: ['дом', 'инвестиция'],
    description: 'Продается ровный участок прямоугольной формы 10 соток в экологически чистом районе Алматы. Идеально под строительство капитального дома.',
    seller: { name: 'Best Realty KZ', phone: '+7 701 123 45 67', isAgency: true, registerDate: '2021 года' },
    createdAt: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: '2',
    slug: 'dacha-kaskelen-6-sotok',
    title: 'Дачный участок с плодоносящим садом',
    price: 4500000,
    area: 6,
    landType: 'Дача',
    purpose: 'Сельхоз',
    location: 'Каскелен, Алматинская обл.',
    image: 'https://images.unsplash.com/photo-1524338198850-8b2fa59a8c08?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1524338198850-8b2fa59a8c08?q=80&w=1000&auto=format&fit=crop'
    ],
    communications: ['Свет', 'Поливная вода'],
    cadastralNumber: '20-315-094-222',
    isPledged: false,
    hasEncumbrances: false,
    hasStateAct: true,
    ownershipType: 'Частная собственность',
    isDivisible: false,
    isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true,
    hasGas: false,
    hasWater: true,
    hasSewer: false,
    hasRoadAccess: true,
    reliefType: 'Под уклон',
    plotShape: 'Квадратный',
    frontWidth: 20,
    depth: 30,
    canChangePurpose: true,
    suitableFor: ['дача', 'сад'],
    description: 'Участок 6 соток. На участке уже растут яблони. Свет заведен, вода поливная + есть своя скважина.',
    seller: { name: 'Анна', phone: '+7 775 987 65 43', isAgency: false, registerDate: '2023 года' },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    slug: 'commerce-talgar-50-sotok',
    title: 'Участок вдоль трассы под СТО',
    price: 120000000,
    area: 50,
    landType: 'Коммерция',
    purpose: 'Коммерция',
    location: 'Талгар, Алматинская обл.',
    image: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=1000&auto=format&fit=crop',
    images: [],
    communications: ['Свет', 'Вода', 'Канализация'],
    cadastralNumber: '20-315-094-333',
    isPledged: true,
    hasEncumbrances: true,
    hasStateAct: true,
    ownershipType: 'Частная собственность',
    isDivisible: true,
    isOnRedLine: true,
    landCategory: 'Земли промышленности',
    hasElectricity: true,
    hasGas: false,
    hasWater: true,
    hasSewer: true,
    hasRoadAccess: true,
    reliefType: 'Ровный',
    plotShape: 'Нестандартный',
    frontWidth: 100,
    depth: 50,
    canChangePurpose: false,
    suitableFor: ['бизнес', 'склад', 'инвестиция'],
    description: 'Коммерческий участок 50 соток вдоль оживленной трассы в Талгаре. Идеально под СТО или торговую базу.',
    seller: { name: 'CommercialInvest', phone: '+7 707 555 11 22', isAgency: true, registerDate: '2019 года' },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '4',
    slug: 'lph-boraldai-15-sotok',
    title: 'Участок под ЛПХ, ровный',
    price: 8000000,
    area: 15,
    landType: 'Сельхоз',
    purpose: 'ЛПХ',
    location: 'Боралдай, Алматинская обл.',
    image: 'https://images.unsplash.com/photo-1500076656116-558758c991c1?q=80&w=1000&auto=format&fit=crop',
    images: [],
    communications: ['Свет', 'Скважина'],
    cadastralNumber: '20-315-094-444',
    isPledged: false,
    hasEncumbrances: false,
    hasStateAct: true,
    ownershipType: 'Частная собственность',
    isDivisible: false,
    isOnRedLine: false,
    landCategory: 'Земли сельскохозяйственного назначения',
    hasElectricity: true,
    hasGas: false,
    hasWater: true,
    hasSewer: false,
    hasRoadAccess: true,
    reliefType: 'Ровный',
    plotShape: 'Прямоугольный',
    frontWidth: 30,
    depth: 50,
    canChangePurpose: true,
    suitableFor: ['дом', 'огород'],
    description: 'Отличный участок для ведения личного подсобного хозяйства (ЛПХ) в Боралдае.',
    seller: { name: 'Ерлан', phone: '+7 747 111 00 99', isAgency: false, registerDate: '2024 года' },
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: '5',
    slug: 'baza-konaev-100-sotok',
    title: 'Зона отдыха у воды',
    price: 250000000,
    area: 100,
    landType: 'Коммерция',
    purpose: 'Коммерция',
    location: 'Конаев, Алматинская обл.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop',
    images: [],
    communications: ['Свет', 'Вода'],
    cadastralNumber: '20-315-094-555',
    isPledged: false,
    hasEncumbrances: false,
    hasStateAct: true,
    ownershipType: 'Аренда',
    isDivisible: true,
    isOnRedLine: false,
    landCategory: 'Земли рекреационного назначения',
    hasElectricity: true,
    hasGas: false,
    hasWater: true,
    hasSewer: true,
    hasRoadAccess: true,
    reliefType: 'Ровный',
    plotShape: 'Прямоугольный',
    frontWidth: 50,
    depth: 200,
    canChangePurpose: false,
    suitableFor: ['инвестиция', 'бизнес'],
    description: 'Участок на берегу Капчагая в Конаеве под строительство зоны отдыха.',
    seller: { name: 'Игорь', phone: '+7 705 333 44 55', isAgency: false, registerDate: '2020 года' },
    createdAt: new Date(Date.now() - 300000000).toISOString(),
  }
];

